#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace ABP_Weaver_Pillar { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Soldier_Jump { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Weaver_OnGround_Aim { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Colossus_Minigun { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Weaver_OnGround { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Fenris_Dash { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_Soldier { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Weaver_AimOffset { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Ursus_OnGround { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_StarfallShip { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Soldier_OnGround { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Consumable_Tag_PostProcess { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Weaver_Dash { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Ursus_Dash { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Soldier_Dash { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Ursus_Jump { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_HangarMech_Trenchwalker { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Prophet_Jump { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_EscapePod_01 { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_wpnHeartbreaker_DMR { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PP_HeartBreaker { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_Weaver_TripleCannon { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Prophet_Dash { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_TrenchWalker_Jump { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_SoldierVeteran_Weapon { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Weaver_RagDoll { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_SoldierVeteran { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Soldier_OnGround_Aim { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Colossus_AimOffset { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_wpnWeaver_Minigun { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Soldier_RagDoll { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_wpnProphet_Hangar_ChargeCannon { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Weaver_Jump { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_Prophet { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_TrenchWalker_Dash { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_Veteran { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_HeartBreaker_OnGround_Aim { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_Fenris { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_wpnFenris_Rocket { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_Weaver { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PP_Fenris { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Fenris_Jump { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_HeartBreaker_Dash { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_HeartBreaker { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_DroneScout { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_Prophet_Sentinel { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_HeartBreaker_OnGround { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_HeartBreaker_Jump { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_wpnTrenchwalker_VampiricPistol { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_wpnTrenchwalker_VampiricPistol { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_Ursus_BeamCannon { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hangar_Ursus { struct FAnimBlueprintGeneratedConstantData; }


namespace ABP_Hunter_Jump
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_wpnSoldier_Auto
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_wpnTrenchwalker_BullpupRifle
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Hunter_OnGround
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace RIG_Soldier
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace RIG_Fenris
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace ABP_R3Destructible
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace RIG_PP_Fenris
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace ABP_DroneScoutMk2
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Hunter_AimOffset
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Hunter_OnGround_Aim
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Colossus
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_wpnProphet_ChargeCannon
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Prophet
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace RIG_Ursus
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace ABP_wpnHeartBreaker_Dmr
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace RIG_Colossus
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace RIG_Prophet
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace ABP_wpnUrsus_AutoShotgun
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_TrenchWalker
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_DroneSentinel
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_GuardMk2
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace RIG_Weaver
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace ABP_Ursus
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Hunter_Dash
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_StarfallTower_Reward
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace RIG_HeartBreaker
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace ABP_BP_DropPod_Anim
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace RIG_Trenchwalker
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace ABP_Soldier
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_wpnWeaver_TripleCannon
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_wpnFenris_Rocket
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_StarfallTower_Extraction
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Weaver
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_wpnWeaver_Minigun
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Fenris
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_DroneGuard
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_HeartBreaker
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
